// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxwgP_pRPtpbdxn0_WjXDDKOb8VbCmcS8',
    appId: '1:307788154487:web:d25bda42938ef8a8eb2872',
    messagingSenderId: '307788154487',
    projectId: 'grocery-43346',
    authDomain: 'grocery-43346.firebaseapp.com',
    storageBucket: 'grocery-43346.appspot.com',
    measurementId: 'G-EZ20EGE3Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA54i61R-iiHYE22x5KEJ8Odx-5uHtEt8g',
    appId: '1:307788154487:android:e16648ba26954254eb2872',
    messagingSenderId: '307788154487',
    projectId: 'grocery-43346',
    storageBucket: 'grocery-43346.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrNQNqvUYuaaqwh2RD-0ziuk22I_YU_dU',
    appId: '1:307788154487:ios:6a2dfcbb318f2834eb2872',
    messagingSenderId: '307788154487',
    projectId: 'grocery-43346',
    storageBucket: 'grocery-43346.appspot.com',
    androidClientId: '307788154487-4bmc3361bt3j6en0bshr9ekcrsuafve8.apps.googleusercontent.com',
    iosClientId: '307788154487-jov1t7slh0092cf05p5jnqrdlivt4528.apps.googleusercontent.com',
    iosBundleId: 'com.example.webAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrNQNqvUYuaaqwh2RD-0ziuk22I_YU_dU',
    appId: '1:307788154487:ios:6a2dfcbb318f2834eb2872',
    messagingSenderId: '307788154487',
    projectId: 'grocery-43346',
    storageBucket: 'grocery-43346.appspot.com',
    androidClientId: '307788154487-4bmc3361bt3j6en0bshr9ekcrsuafve8.apps.googleusercontent.com',
    iosClientId: '307788154487-jov1t7slh0092cf05p5jnqrdlivt4528.apps.googleusercontent.com',
    iosBundleId: 'com.example.webAdminPanel',
  );
}
